### ISSUE TITLE
Switching switches sometimes lead to a null pointer exception

### ISSUE THREAD

**Issue by ollie-dev** [ollie-dev/openhab2-addons#12]
Hi Ollie,

schalte ich genau den im vorigen Post erwähnten Außenzwischenstecker, dann passiert folgendes

```
Code:
10:59:07.535 [DEBUG] [marthome.handler.InnogyDeviceHandler] - handleCommand called for channel 'innogysmarthome:PSSO:SMARTHOME06:7a895f5ad58745fd9edf75cf3cf7da76:switch' of type 'PSSO' with command 'ON'
10:59:07.537 [DEBUG] [home.internal.DeviceStructureManager] - getDeviceById 7a895f5ad58745fd9edf75cf3cf7da76:true
10:59:08.306 [INFO ] [marthome.event.ItemStateChangedEvent] - zbv3_outdoor changed from OFF to ON
10:59:11.216 [DEBUG] [gysmarthome.internal.InnogyWebSocket] - innogy WebSocket onMessage() - [{"type":"device/SHC.RWE/1.0/event/StateChanged","timestamp":"2016-12-09T09:59:04.4130000Z","desc":"/desc/device/SHC.RWE/1.0/event/StateChanged","link":{"value":"/capability/ad90047515274f47a82c6f38e460c752"},"Properties":[{"name":"OnState","value":true,"lastchanged":"2016-12-09T09:59:04.3960000Z"}]}]
10:59:11.217 [DEBUG] [marthome.handler.InnogyBridgeHandler] - onEvent called. Msg: [{"type":"device/SHC.RWE/1.0/event/StateChanged","timestamp":"2016-12-09T09:59:04.4130000Z","desc":"/desc/device/SHC.RWE/1.0/event/StateChanged","link":{"value":"/capability/ad90047515274f47a82c6f38e460c752"},"Properties":[{"name":"OnState","value":true,"lastchanged":"2016-12-09T09:59:04.3960000Z"}]}]
10:59:11.229 [DEBUG] [marthome.handler.InnogyBridgeHandler] - Event found: Type:device/SHC.RWE/1.0/event/StateChanged Capability:/capability/ad90047515274f47a82c6f38e460c752
10:59:11.231 [DEBUG] [marthome.handler.InnogyDeviceHandler] - DeviceId 7a895f5ad58745fd9edf75cf3cf7da76 relevant for this handler.
10:59:11.233 [DEBUG] [marthome.handler.InnogyDeviceHandler] - State changed OnState to true.
10:59:11.234 [DEBUG] [marthome.handler.InnogyDeviceHandler] - Loaded Capability SwitchActuator, Switch with id ad90047515274f47a82c6f38e460c752, device /device/7a895f5ad58745fd9edf75cf3cf7da76 from device id 7a895f5ad58745fd9edf75cf3cf7da76
10:59:11.236 [ERROR] [marthome.handler.InnogyBridgeHandler] - Error with Event: {}
java.lang.NullPointerException
       at org.openhab.binding.innogysmarthome.handler.InnogyDeviceHandler.onDeviceStateChanged(InnogyDeviceHandler.java:321)
       at org.openhab.binding.innogysmarthome.handler.InnogyBridgeHandler.onEvent(InnogyBridgeHandler.java:452)
       at org.openhab.binding.innogysmarthome.internal.InnogyWebSocket.onMessage(InnogyWebSocket.java:63)
       at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_111]
       at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_111]
       at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:71)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:72)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextMessage(JettyAnnotatedEventDriver.java:234)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextFrame(JettyAnnotatedEventDriver.java:226)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:376)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:679)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:511)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:202)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
10:59:11.602 [DEBUG] [gysmarthome.internal.InnogyWebSocket] - innogy WebSocket onMessage() - [{"type":"device/SHC.RWE/1.0/event/StateChanged","timestamp":"2016-12-09T09:59:04.4130000Z","desc":"/desc/device/SHC.RWE/1.0/event/StateChanged","link":{"value":"/capability/ad90047515274f47a82c6f38e460c752"},"Properties":[{"name":"OnState","value":true,"lastchanged":"2016-12-09T09:59:04.3960000Z"}]}]
10:59:11.603 [DEBUG] [marthome.handler.InnogyBridgeHandler] - onEvent called. Msg: [{"type":"device/SHC.RWE/1.0/event/StateChanged","timestamp":"2016-12-09T09:59:04.4130000Z","desc":"/desc/device/SHC.RWE/1.0/event/StateChanged","link":{"value":"/capability/ad90047515274f47a82c6f38e460c752"},"Properties":[{"name":"OnState","value":true,"lastchanged":"2016-12-09T09:59:04.3960000Z"}]}]
10:59:11.606 [DEBUG] [marthome.handler.InnogyBridgeHandler] - Event found: Type:device/SHC.RWE/1.0/event/StateChanged Capability:/capability/ad90047515274f47a82c6f38e460c752
10:59:11.607 [DEBUG] [marthome.handler.InnogyDeviceHandler] - DeviceId 7a895f5ad58745fd9edf75cf3cf7da76 relevant for this handler.
10:59:11.608 [DEBUG] [marthome.handler.InnogyDeviceHandler] - State changed OnState to true.
10:59:11.608 [DEBUG] [marthome.handler.InnogyDeviceHandler] - Loaded Capability SwitchActuator, Switch with id ad90047515274f47a82c6f38e460c752, device /device/7a895f5ad58745fd9edf75cf3cf7da76 from device id 7a895f5ad58745fd9edf75cf3cf7da76
10:59:11.609 [ERROR] [marthome.handler.InnogyBridgeHandler] - Error with Event: {}
java.lang.NullPointerException
       at org.openhab.binding.innogysmarthome.handler.InnogyDeviceHandler.onDeviceStateChanged(InnogyDeviceHandler.java:321)
       at org.openhab.binding.innogysmarthome.handler.InnogyBridgeHandler.onEvent(InnogyBridgeHandler.java:452)
       at org.openhab.binding.innogysmarthome.internal.InnogyWebSocket.onMessage(InnogyWebSocket.java:63)
       at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_111]
       at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_111]
       at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:71)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:72)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextMessage(JettyAnnotatedEventDriver.java:234)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextFrame(JettyAnnotatedEventDriver.java:226)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:376)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:679)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:511)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:202)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
       at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]

```
Schalte ich andere Zwischenstecker, passiert der Fehler nicht.

**Comment by ollie-dev** [comment]
Not reproducible.
