### ISSUE TITLE
Support event StateChanged for SHC updates

### ISSUE THREAD

**Issue by ollie-dev** [ollie-dev/openhab2-addons#3]
When an SHC update is started via innogy app, the following sequence begins:

1. Software download
```2016-11-16 22:03:39.891 [DEBUG] [o.b.i.internal.InnogyWebSocket:61   ] - innogy WebSocket onMessage() - [{"type":"device/SHC.RWE/1.0/event/StateChanged","timestamp":"2016-11-16T21:03:35.0530000Z","desc":"/desc/device/SHC.RWE/1.0/event/StateChanged","link":{"value":"/device/b0f441a410f8465fbede93a7363a4339"},"Properties":[{"name":"UpdateAvailable","value":"1.913-2.0.544.0","lastchanged":"2016-11-04T03:39:13.2100000Z"},{"name":"LastReboot","value":"2016-11-04T04:37:55.837+01:00","lastchanged":"2016-11-04T03:39:13.2100000Z"},{"name":"MBusDongleAttached","value":false,"lastchanged":"2016-11-04T03:39:13.2420000Z"},{"name":"LBDongleAttached","value":false,"lastchanged":"2016-11-04T03:39:13.2420000Z"},{"name":"ConfigVersion","value":122.0,"lastchanged":"2016-11-16T20:56:41.2360000Z"},{"name":"OSState","value":"Downloading","lastchanged":"2016-11-16T21:03:35.0130000Z"},{"name":"MemoryLoad","value":62.0,"lastchanged":"2016-11-16T20:28:59.7290000Z"},{"name":"CPULoad","value":20.0,"lastchanged":"2016-11-16T21:03:35.0520000Z"}]}]
2016-11-16 22:03:39.892 [DEBUG] [.i.handler.InnogyBridgeHandler:408  ] - onEvent called. Msg: [{"type":"device/SHC.RWE/1.0/event/StateChanged","timestamp":"2016-11-16T21:03:35.0530000Z","desc":"/desc/device/SHC.RWE/1.0/event/StateChanged","link":{"value":"/device/b0f441a410f8465fbede93a7363a4339"},"Properties":[{"name":"UpdateAvailable","value":"1.913-2.0.544.0","lastchanged":"2016-11-04T03:39:13.2100000Z"},{"name":"LastReboot","value":"2016-11-04T04:37:55.837+01:00","lastchanged":"2016-11-04T03:39:13.2100000Z"},{"name":"MBusDongleAttached","value":false,"lastchanged":"2016-11-04T03:39:13.2420000Z"},{"name":"LBDongleAttached","value":false,"lastchanged":"2016-11-04T03:39:13.2420000Z"},{"name":"ConfigVersion","value":122.0,"lastchanged":"2016-11-16T20:56:41.2360000Z"},{"name":"OSState","value":"Downloading","lastchanged":"2016-11-16T21:03:35.0130000Z"},{"name":"MemoryLoad","value":62.0,"lastchanged":"2016-11-16T20:28:59.7290000Z"},{"name":"CPULoad","value":20.0,"lastchanged":"2016-11-16T21:03:35.0520000Z"}]}]
2016-11-16 22:03:39.893 [DEBUG] [.i.handler.InnogyBridgeHandler:414  ] - Event found: Type:device/SHC.RWE/1.0/event/StateChanged Capability:/device/b0f441a410f8465fbede93a7363a4339
2016-11-16 22:03:39.893 [DEBUG] [.i.handler.InnogyBridgeHandler:428  ] - link type /device/ not supported (yet?)```

2. SHC OSState rebooting
```2016-11-16 22:03:46.728 [DEBUG] [o.b.i.internal.InnogyWebSocket:61   ] - innogy WebSocket onMessage() - [{"type":"device/SHC.RWE/1.0/event/StateChanged","timestamp":"2016-11-16T21:03:42.2160000Z","desc":"/desc/device/SHC.RWE/1.0/event/StateChanged","link":{"value":"/device/b0f441a410f8465fbede93a7363a4339"},"Properties":[{"name":"UpdateAvailable","value":"1.913-2.0.544.0","lastchanged":"2016-11-04T03:39:13.2100000Z"},{"name":"LastReboot","value":"2016-11-04T04:37:55.837+01:00","lastchanged":"2016-11-04T03:39:13.2100000Z"},{"name":"MBusDongleAttached","value":false,"lastchanged":"2016-11-04T03:39:13.2420000Z"},{"name":"LBDongleAttached","value":false,"lastchanged":"2016-11-04T03:39:13.2420000Z"},{"name":"ConfigVersion","value":122.0,"lastchanged":"2016-11-16T20:56:41.2360000Z"},{"name":"OSState","value":"Rebooting","lastchanged":"2016-11-16T21:03:42.1830000Z"},{"name":"MemoryLoad","value":62.0,"lastchanged":"2016-11-16T20:28:59.7290000Z"},{"name":"CPULoad","value":95.0,"lastchanged":"2016-11-16T21:03:42.2150000Z"}]}]
2016-11-16 22:03:46.728 [DEBUG] [.i.handler.InnogyBridgeHandler:408  ] - onEvent called. Msg: [{"type":"device/SHC.RWE/1.0/event/StateChanged","timestamp":"2016-11-16T21:03:42.2160000Z","desc":"/desc/device/SHC.RWE/1.0/event/StateChanged","link":{"value":"/device/b0f441a410f8465fbede93a7363a4339"},"Properties":[{"name":"UpdateAvailable","value":"1.913-2.0.544.0","lastchanged":"2016-11-04T03:39:13.2100000Z"},{"name":"LastReboot","value":"2016-11-04T04:37:55.837+01:00","lastchanged":"2016-11-04T03:39:13.2100000Z"},{"name":"MBusDongleAttached","value":false,"lastchanged":"2016-11-04T03:39:13.2420000Z"},{"name":"LBDongleAttached","value":false,"lastchanged":"2016-11-04T03:39:13.2420000Z"},{"name":"ConfigVersion","value":122.0,"lastchanged":"2016-11-16T20:56:41.2360000Z"},{"name":"OSState","value":"Rebooting","lastchanged":"2016-11-16T21:03:42.1830000Z"},{"name":"MemoryLoad","value":62.0,"lastchanged":"2016-11-16T20:28:59.7290000Z"},{"name":"CPULoad","value":95.0,"lastchanged":"2016-11-16T21:03:42.2150000Z"}]}]
2016-11-16 22:03:46.730 [DEBUG] [.i.handler.InnogyBridgeHandler:414  ] - Event found: Type:device/SHC.RWE/1.0/event/StateChanged Capability:/device/b0f441a410f8465fbede93a7363a4339
2016-11-16 22:03:46.730 [DEBUG] [.i.handler.InnogyBridgeHandler:428  ] - link type /device/ not supported (yet?)
```

3. Disconnect event
```2016-11-16 22:03:53.703 [DEBUG] [o.b.i.internal.InnogyWebSocket:61   ] - innogy WebSocket onMessage() - [{"type":"/event/Disconnect","timestamp":"2016-11-16T21:03:53.6885803Z","desc":"/desc/event/Disconnect","Properties":[{"name":"Reason","value":"SoftwareUpdate"}]}]
2016-11-16 22:03:53.703 [DEBUG] [.i.handler.InnogyBridgeHandler:408  ] - onEvent called. Msg: [{"type":"/event/Disconnect","timestamp":"2016-11-16T21:03:53.6885803Z","desc":"/desc/event/Disconnect","Properties":[{"name":"Reason","value":"SoftwareUpdate"}]}]
2016-11-16 22:03:53.718 [ERROR] [.i.handler.InnogyBridgeHandler:450  ] - Error with Event: {}java.lang.NullPointerException: null
	at org.openhab.binding.innogysmarthome.handler.InnogyBridgeHandler.onEvent(InnogyBridgeHandler.java:414)
	at org.openhab.binding.innogysmarthome.internal.InnogyWebSocket.onMessage(InnogyWebSocket.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:71)
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:72)
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextMessage(JettyAnnotatedEventDriver.java:234)
	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66)

java.lang.NullPointerException
	at org.openhab.binding.innogysmarthome.handler.InnogyBridgeHandler.onEvent(InnogyBridgeHandler.java:414)
	at org.openhab.binding.innogysmarthome.internal.InnogyWebSocket.onMessage(InnogyWebSocket.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:71)
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:72)
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextMessage(JettyAnnotatedEventDriver.java:234)
	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66)
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextFrame(JettyAnnotatedEventDriver.java:226)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162)
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:376)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:679)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:511)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:202)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
2016-11-16 22:03:53.722 [INFO ] [o.b.i.internal.InnogyWebSocket:41   ] - Connection to innogy WebSocket was closed (code: 1000). Reason: null
```

Today, after WebSocket was closed, the WebSocket is reconnected immediately. 

4. Controller connectivity changes to unreachable
```
2016-11-16 22:04:06.706 [DEBUG] [o.b.i.internal.InnogyWebSocket:61   ] - innogy WebSocket onMessage() - [{"type":"device/SHC.RWE/1.0/event/ControllerConnectivityChanged","timestamp":"2016-11-16T21:04:06.6575212Z","desc":"/desc/device/SHC.RWE/1.0/event/ControllerConnectivityChanged","link":{"value":"/desc/device/SHC.RWE/1.0"},"Properties":[{"name":"IsConnected","value":false}],"Data":[]}]
2016-11-16 22:04:06.706 [DEBUG] [.i.handler.InnogyBridgeHandler:408  ] - onEvent called. Msg: [{"type":"device/SHC.RWE/1.0/event/ControllerConnectivityChanged","timestamp":"2016-11-16T21:04:06.6575212Z","desc":"/desc/device/SHC.RWE/1.0/event/ControllerConnectivityChanged","link":{"value":"/desc/device/SHC.RWE/1.0"},"Properties":[{"name":"IsConnected","value":false}],"Data":[]}]
2016-11-16 22:04:06.707 [DEBUG] [.i.handler.InnogyBridgeHandler:414  ] - Event found: Type:device/SHC.RWE/1.0/event/ControllerConnectivityChanged Capability:/desc/device/SHC.RWE/1.0
2016-11-16 22:04:06.707 [DEBUG] [.i.handler.InnogyBridgeHandler:445  ] - Unknown eventtype device/SHC.RWE/1.0/event/ControllerConnectivityChanged.
```

5. Controller connectivity changes to reachable again
```
2016-11-16 22:06:15.906 [DEBUG] [o.b.i.internal.InnogyWebSocket:61   ] - innogy WebSocket onMessage() - [{"type":"device/SHC.RWE/1.0/event/ControllerConnectivityChanged","timestamp":"2016-11-16T21:06:15.6454458Z","desc":"/desc/device/SHC.RWE/1.0/event/ControllerConnectivityChanged","link":{"value":"/desc/device/SHC.RWE/1.0"},"Properties":[{"name":"IsConnected","value":true}],"Data":[]}]
2016-11-16 22:06:15.910 [DEBUG] [.i.handler.InnogyBridgeHandler:408  ] - onEvent called. Msg: [{"type":"device/SHC.RWE/1.0/event/ControllerConnectivityChanged","timestamp":"2016-11-16T21:06:15.6454458Z","desc":"/desc/device/SHC.RWE/1.0/event/ControllerConnectivityChanged","link":{"value":"/desc/device/SHC.RWE/1.0"},"Properties":[{"name":"IsConnected","value":true}],"Data":[]}]
2016-11-16 22:06:15.911 [DEBUG] [.i.handler.InnogyBridgeHandler:414  ] - Event found: Type:device/SHC.RWE/1.0/event/ControllerConnectivityChanged Capability:/desc/device/SHC.RWE/1.0
2016-11-16 22:06:15.911 [DEBUG] [.i.handler.InnogyBridgeHandler:445  ] - Unknown eventtype device/SHC.RWE/1.0/event/ControllerConnectivityChanged.
```

While the WebSocket still seems to work, the binding crashes with the next action, because the Session is invalid after SHC reboot. Example switching a VariableActuator:
```
2016-11-16 22:06:47.946 [DEBUG] [.i.handler.InnogyDeviceHandler:60   ] - handleCommand called for channel 'innogysmarthome:VariableActuator:SMARTHOME06:155f38e4ee2047c0b2246133b1de96a0:switch' of type 'VariableActuator' with command 'ON'
2016-11-16 22:06:47.947 [DEBUG] [o.b.i.i.DeviceStructureManager:128  ] - getDeviceById 155f38e4ee2047c0b2246133b1de96a0:true
2016-11-16 22:06:48.164 [ERROR] [.i.handler.InnogyBridgeHandler:572  ] - Unexcepted API error: Session not found
2016-11-16 22:06:48.166 [DEBUG] [.i.handler.InnogyBridgeHandler:309  ] - Disposing innogy SmartHome bridge handler 'SMARTHOME06'
2016-11-16 22:06:48.166 [DEBUG] [.i.handler.InnogyDeviceHandler:96   ] - bridgeStatusChanged OFFLINE (COMMUNICATION_ERROR): Session not found
```

So when the bridge goes offline, the binding must dispose and schedule a reinitialization.

**Comment by ollie-dev** [comment]
Should be fixed. Cannot test without available software updates. Closed.
