### ISSUE TITLE
WebSocket SocketTimeoutException

### ISSUE THREAD

**Issue by ollie-dev** [ollie-dev/openhab2-addons#34]
```
2017-05-01 03:17:41.819 [ERROR] [gysmarthome.internal.InnogyWebSocket] - innogy WebSocket onError() - Timeout on Read
2017-05-01 03:17:41.837 [INFO ] [gysmarthome.internal.InnogyWebSocket] - Connection to innogy WebSocket was closed (code: 1001). Reason: Idle Timeout
2017-05-01 03:17:41.837 [DEBUG] [marthome.handler.InnogyBridgeHandler] - onEventRunnerStopped called
2017-05-01 03:17:41.838 [DEBUG] [marthome.handler.InnogyBridgeHandler] - WebSocket URL: wss://api.services-smarthome.de/API/1.0/events?token=eyJ0eXAiOiJKV1QiL...cWKKrQHQ7A
2017-05-01 03:17:41.840 [INFO ] [marthome.handler.InnogyBridgeHandler] - Starting innogy websocket.
2017-05-01 03:17:41.868 [DEBUG] [gysmarthome.internal.InnogyWebSocket] - Connecting to innogy WebSocket...
2017-05-01 03:17:56.895 [ERROR] [gysmarthome.internal.InnogyWebSocket] - innogy WebSocket onError() - Connect Timeout
2017-05-01 03:17:56.896 [ERROR] [marthome.handler.InnogyBridgeHandler] - Unknown exception
java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: Connect Timeout
        at org.eclipse.jetty.util.FuturePromise.get(FuturePromise.java:123)
        at org.openhab.binding.innogysmarthome.internal.InnogyWebSocket.start(InnogyWebSocket.java:67)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.openhab.binding.innogysmarthome.handler.InnogyBridgeHandler$WebSocketRunner.run(InnogyBridgeHandler.java:181)
        at org.openhab.binding.innogysmarthome.handler.InnogyBridgeHandler.onEventRunnerStopped(InnogyBridgeHandler.java:591)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.openhab.binding.innogysmarthome.handler.InnogyBridgeHandler.onEventRunnerStopped(InnogyBridgeHandler.java:601)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.openhab.binding.innogysmarthome.internal.InnogyWebSocket.onClose(InnogyWebSocket.java:96)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_101]
        at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:71)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:72)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onClose(JettyAnnotatedEventDriver.java:139)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.websocket.common.WebSocketSession.notifyClose(WebSocketSession.java:414)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.websocket.common.WebSocketSession.onConnectionStateChange(WebSocketSession.java:445)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.websocket.common.io.IOState.notifyStateListeners(IOState.java:184)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.websocket.common.io.IOState.onAbnormalClose(IOState.java:219)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection$OnCloseLocalCallback.onLocalClose(AbstractWebSocketConnection.java:165)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection$OnCloseLocalCallback.writeSuccess(AbstractWebSocketConnection.java:155)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.websocket.common.io.FrameFlusher.notifyCallbackSuccess(FrameFlusher.java:407)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.websocket.common.io.FrameFlusher$Flusher.succeedEntries(FrameFlusher.java:242)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.websocket.common.io.FrameFlusher$Flusher.succeeded(FrameFlusher.java:232)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:332)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:140)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.websocket.common.io.FrameFlusher$Flusher.flush(FrameFlusher.java:153)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.websocket.common.io.FrameFlusher$Flusher.process(FrameFlusher.java:217)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.websocket.common.io.FrameFlusher.enqueue(FrameFlusher.java:382)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.outgoingFrame(AbstractWebSocketConnection.java:614)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.websocket.client.io.WebSocketClientConnection.outgoingFrame(WebSocketClientConnection.java:85)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.close(AbstractWebSocketConnection.java:289)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.close(AbstractWebSocketConnection.java:283)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onReadTimeout(AbstractWebSocketConnection.java:597)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.io.AbstractConnection.onFillInterestedFailed(AbstractConnection.java:168)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillInterestedFailed(AbstractWebSocketConnection.java:538)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.failed(AbstractConnection.java:279)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.io.FillInterest.onFail(FillInterest.java:125)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.io.ssl.SslConnection.onFillInterestedFailed(SslConnection.java:226)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.failed(AbstractConnection.java:279)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.io.FillInterest.onFail(FillInterest.java:125)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:166)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_101]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_101]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_101]
Caused by: java.net.SocketTimeoutException: Connect Timeout
        at org.eclipse.jetty.io.ManagedSelector$ConnectTimeout.run(ManagedSelector.java:683)[231:org.openhab.binding.innogysmarthome:2.1.0.201704301903]
        ... 7 more
2017-05-01 03:17:56.916 [DEBUG] [marthome.handler.InnogyBridgeHandler] - Disposing innogy SmartHome bridge handler 'SMARTHOME06'
2017-05-01 03:17:56.916 [INFO ] [n.ollie.innogysmarthome.InnogyClient] - Uninitializing innogy SmartHome Session...
2017-05-01 03:18:08.844 [DEBUG] [n.ollie.innogysmarthome.InnogyClient] - [32] Statuscode is OK.
2017-05-01 03:18:08.845 [INFO ] [marthome.handler.InnogyBridgeHandler] - innogy SmartHome bridge handler shut down.
2017-05-01 03:18:08.845 [INFO ] [marthome.handler.InnogyBridgeHandler] - Scheduling reinitialize in 30 seconds.
2017-05-01 03:18:08.846 [ERROR] [marthome.handler.InnogyBridgeHandler] - Error starting websocket.
2017-05-01 03:18:38.846 [DEBUG] [marthome.handler.InnogyBridgeHandler] - Initializing innogy SmartHome BridgeHandler...
```

**Comment by ollie-dev** [comment]
Fixed.
