### ISSUE TITLE
WebSocket Connection timeout not caught properly

### ISSUE THREAD

**Issue by ollie-dev** [ollie-dev/openhab2-addons#5]
```
2016-12-04 04:47:49.258 [INFO ] [gysmarthome.internal.InnogyWebSocket] - Connection to innogy WebSocket was closed (code: 1006). Reason: WebSocket Read EOF
2016-12-04 04:47:49.259 [INFO ] [marthome.handler.InnogyBridgeHandler] - Starting web socket.
2016-12-04 04:48:04.298 [WARN ] [gysmarthome.internal.InnogyWebSocket] - Error with innogy WebSocket: {}
java.net.SocketTimeoutException: Connect Timeout
        at org.eclipse.jetty.io.ManagedSelector$ConnectTimeout.run(ManagedSelector.java:683)[213:org.openhab.binding.innogysmarthome:2.0.0.201612032223]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_101]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_101]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_101]
2016-12-04 04:48:04.307 [ERROR] [marthome.handler.InnogyBridgeHandler] - Unknown exception
java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: Connect Timeout
        at org.eclipse.jetty.util.FuturePromise.get(FuturePromise.java:123)
        at org.openhab.binding.innogysmarthome.handler.InnogyBridgeHandler$WebSocketRunner.run(InnogyBridgeHandler.java:183)
        at org.openhab.binding.innogysmarthome.handler.InnogyBridgeHandler.onEventRunnerStopped(InnogyBridgeHandler.java:485)
        at org.openhab.binding.innogysmarthome.handler.InnogyBridgeHandler.onEventRunnerStopped(InnogyBridgeHandler.java:495)
        at org.openhab.binding.innogysmarthome.internal.InnogyWebSocket.onClose(InnogyWebSocket.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_101]
        at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:71)[213:org.openhab.binding.innogysmarthome:2.0.0.201612032223]
        at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:72)[213:org.openhab.binding.innogysmarthome:2.0.0.201612032223]
        at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onClose(JettyAnnotatedEventDriver.java:139)[213:org.openhab.binding.innogysmarthome:2.0.0.201612032223]
        at org.eclipse.jetty.websocket.common.WebSocketSession.notifyClose(WebSocketSession.java:414)[213:org.openhab.binding.innogysmarthome:2.0.0.201612032223]
        at org.eclipse.jetty.websocket.common.WebSocketSession.onConnectionStateChange(WebSocketSession.java:445)[213:org.openhab.binding.innogysmarthome:2.0.0.201612032223]
        at org.eclipse.jetty.websocket.common.io.IOState.notifyStateListeners(IOState.java:184)[213:org.openhab.binding.innogysmarthome:2.0.0.201612032223]
        at org.eclipse.jetty.websocket.common.io.IOState.onReadFailure(IOState.java:498)[213:org.openhab.binding.innogysmarthome:2.0.0.201612032223]
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:666)[213:org.openhab.binding.innogysmarthome:2.0.0.201612032223]
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:511)[213:org.openhab.binding.innogysmarthome:2.0.0.201612032223]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)[213:org.openhab.binding.innogysmarthome:2.0.0.201612032223]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)[213:org.openhab.binding.innogysmarthome:2.0.0.201612032223]
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:202)[213:org.openhab.binding.innogysmarthome:2.0.0.201612032223]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)[213:org.openhab.binding.innogysmarthome:2.0.0.201612032223]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)[213:org.openhab.binding.innogysmarthome:2.0.0.201612032223]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)[213:org.openhab.binding.innogysmarthome:2.0.0.201612032223]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)[213:org.openhab.binding.innogysmarthome:2.0.0.201612032223]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)[213:org.openhab.binding.innogysmarthome:2.0.0.201612032223]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)[213:org.openhab.binding.innogysmarthome:2.0.0.201612032223]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)[213:org.openhab.binding.innogysmarthome:2.0.0.201612032223]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)[213:org.openhab.binding.innogysmarthome:2.0.0.201612032223]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_101]
Caused by: java.net.SocketTimeoutException: Connect Timeout
        at org.eclipse.jetty.io.ManagedSelector$ConnectTimeout.run(ManagedSelector.java:683)[213:org.openhab.binding.innogysmarthome:2.0.0.201612032223]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_101]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_101]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_101]
        ... 1 more
2016-12-04 04:48:04.901 [INFO ] [marthome.handler.InnogyBridgeHandler] - Scheduling reinitialize in 30 seconds.
2016-12-04 04:48:04.903 [ERROR] [marthome.handler.InnogyBridgeHandler] - Error starting Websocket.
2016-12-04 04:48:34.904 [INFO ] [marthome.handler.InnogyBridgeHandler] - Initializing innogy SmartHome client...
```

**Comment by ollie-dev** [comment]
Unsure, if really a bug. However, can be caught better. See commit.
