### ISSUE TITLE
Connecting devices throws null pointer exception - state not available?

### ISSUE THREAD

**Issue by ollie-dev** [ollie-dev/openhab2-addons#9]
```
10:24:13.393 [DEBUG] [gysmarthome.internal.InnogyWebSocket] - innogy WebSocket onMessage() - [{"type":"device/SHC.RWE/1.0/event/StateChanged","timestamp":"2016-12-09T09:24:06.7520000Z","desc":"/desc/device/SHC.RWE/1.0/event/StateChanged","link":{"value":"/device/7a895f5ad58745fd9edf75cf3cf7da76"},"Properties":[{"name":"IsReachable","value":true,"lastchanged":"2016-12-09T09:24:06.7240000Z"},{"name":"DeviceConfigurationState","value":"Complete","lastchanged":"2016-12-06T16:09:33.3870000Z"},{"name":"DeviceInclusionState","value":"Included","lastchanged":"2016-12-06T16:09:32.0220000Z"},{"name":"UpdateState","value":"UpToDate","lastchanged":"0001-01-01T00:00:00.0000000Z"},{"name":"FirmwareVersion","value":"1.7","lastchanged":"2016-12-09T09:24:06.7510000Z"}]},{"type":"device/SHC.RWE/1.0/event/MessageDeleted","timestamp":"2016-12-09T09:24:07.0270000Z","desc":"/desc/device/SHC.RWE/1.0/event/MessageDeleted","link":{"value":"/message/d7cefe8f085241d0bb301e06d3a3e210"}},{"type":"device/SHC.RWE/1.0/event/StateChanged","timestamp":"2016-12-09T09:24:07.7450000Z","desc":"/desc/device/SHC.RWE/1.0/event/StateChanged","link":{"value":"/capability/ad90047515274f47a82c6f38e460c752"},"Properties":[{"name":"OnState","value":false,"lastchanged":"2016-12-09T09:24:07.7230000Z"}]}]
10:24:13.401 [DEBUG] [marthome.handler.InnogyBridgeHandler] - onEvent called. Msg: [{"type":"device/SHC.RWE/1.0/event/StateChanged","timestamp":"2016-12-09T09:24:06.7520000Z","desc":"/desc/device/SHC.RWE/1.0/event/StateChanged","link":{"value":"/device/7a895f5ad58745fd9edf75cf3cf7da76"},"Properties":[{"name":"IsReachable","value":true,"lastchanged":"2016-12-09T09:24:06.7240000Z"},{"name":"DeviceConfigurationState","value":"Complete","lastchanged":"2016-12-06T16:09:33.3870000Z"},{"name":"DeviceInclusionState","value":"Included","lastchanged":"2016-12-06T16:09:32.0220000Z"},{"name":"UpdateState","value":"UpToDate","lastchanged":"0001-01-01T00:00:00.0000000Z"},{"name":"FirmwareVersion","value":"1.7","lastchanged":"2016-12-09T09:24:06.7510000Z"}]},{"type":"device/SHC.RWE/1.0/event/MessageDeleted","timestamp":"2016-12-09T09:24:07.0270000Z","desc":"/desc/device/SHC.RWE/1.0/event/MessageDeleted","link":{"value":"/message/d7cefe8f085241d0bb301e06d3a3e210"}},{"type":"device/SHC.RWE/1.0/event/StateChanged","timestamp":"2016-12-09T09:24:07.7450000Z","desc":"/desc/device/SHC.RWE/1.0/event/StateChanged","link":{"value":"/capability/ad90047515274f47a82c6f38e460c752"},"Properties":[{"name":"OnState","value":false,"lastchanged":"2016-12-09T09:24:07.7230000Z"}]}]
10:24:13.412 [DEBUG] [marthome.handler.InnogyBridgeHandler] - Event found: Type:device/SHC.RWE/1.0/event/StateChanged Capability:/device/7a895f5ad58745fd9edf75cf3cf7da76
10:24:13.414 [DEBUG] [home.internal.DeviceStructureManager] - getDeviceById 7a895f5ad58745fd9edf75cf3cf7da76:true
10:24:13.416 [DEBUG] [marthome.handler.InnogyBridgeHandler] - DEVICE STATE CHANGED!!!
10:24:13.417 [DEBUG] [marthome.handler.InnogyDeviceHandler] - DeviceId 7a895f5ad58745fd9edf75cf3cf7da76 relevant for this handler.
10:24:13.419 [DEBUG] [marthome.handler.InnogyDeviceHandler] - State changed IsReachable to true.
10:24:13.421 [DEBUG] [marthome.handler.InnogyDeviceHandler] - State changed DeviceConfigurationState to Complete.
10:24:13.422 [DEBUG] [marthome.handler.InnogyDeviceHandler] - State changed DeviceInclusionState to Included.
10:24:13.424 [DEBUG] [marthome.handler.InnogyDeviceHandler] - State changed UpdateState to UpToDate.
10:24:13.426 [DEBUG] [marthome.handler.InnogyDeviceHandler] - State changed FirmwareVersion to 1.7.
10:24:13.427 [DEBUG] [marthome.handler.InnogyDeviceHandler] - onDeviceStateChanged called with device Lichterkette/7a895f5ad58745fd9edf75cf3cf7da76
10:24:13.431 [DEBUG] [marthome.handler.InnogyDeviceHandler] - ->capability:ad90047515274f47a82c6f38e460c752 (SwitchActuator/Switch)
10:24:13.433 [DEBUG] [marthome.handler.InnogyDeviceHandler] - Capability not available for device Lichterkette (PSSO)
10:24:13.437 [DEBUG] [marthome.handler.InnogyBridgeHandler] - Event found: Type:device/SHC.RWE/1.0/event/MessageDeleted Capability:/message/d7cefe8f085241d0bb301e06d3a3e210
10:24:13.439 [DEBUG] [marthome.handler.InnogyBridgeHandler] - Unknown eventtype device/SHC.RWE/1.0/event/MessageDeleted.
10:24:13.441 [DEBUG] [marthome.handler.InnogyBridgeHandler] - Event found: Type:device/SHC.RWE/1.0/event/StateChanged Capability:/capability/ad90047515274f47a82c6f38e460c752
10:24:13.444 [DEBUG] [marthome.handler.InnogyDeviceHandler] - DeviceId 7a895f5ad58745fd9edf75cf3cf7da76 relevant for this handler.
10:24:13.446 [DEBUG] [marthome.handler.InnogyDeviceHandler] - State changed OnState to false.
10:24:13.449 [DEBUG] [marthome.handler.InnogyDeviceHandler] - Loaded Capability SwitchActuator, Switch with id ad90047515274f47a82c6f38e460c752, device /device/7a895f5ad58745fd9edf75cf3cf7da76 from device id 7a895f5ad58745fd9edf75cf3cf7da76
10:24:13.452 [ERROR] [marthome.handler.InnogyBridgeHandler] - Error with Event: {}
java.lang.NullPointerException
        at org.openhab.binding.innogysmarthome.handler.InnogyDeviceHandler.onDeviceStateChanged(InnogyDeviceHandler.java:321)
        at org.openhab.binding.innogysmarthome.handler.InnogyBridgeHandler.onEvent(InnogyBridgeHandler.java:452)
        at org.openhab.binding.innogysmarthome.internal.InnogyWebSocket.onMessage(InnogyWebSocket.java:63)
        at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_111]
        at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:71)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:72)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextMessage(JettyAnnotatedEventDriver.java:234)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextFrame(JettyAnnotatedEventDriver.java:226)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:376)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:679)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:511)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:202)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)[210:org.openhab.binding.innogysmarthome:2.0.0.201612072035]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
10:26:42.684 [INFO ] [gysmarthome.internal.InnogyWebSocket] - Connection to innogy WebSocket was closed (code: 1000). Reason: null
10:26:42.687 [INFO ] [marthome.handler.InnogyBridgeHandler] - Starting web socket.
10:26:42.688 [DEBUG] [marthome.handler.InnogyBridgeHandler] - WebSocket URL: wss://api.services-smarthome.de/API/1.0/events?token=blablubbbb
10:26:42.990 [INFO ] [gysmarthome.internal.InnogyWebSocket] - Connected to innogy WebSocket.
10:26:42.996 [DEBUG] [gysmarthome.internal.InnogyWebSocket] - innogy Websocket session: WebSocketSession[websocket=JettyAnnotatedEventDriver[org.openhab.binding.innogysmarthome.internal.InnogyWebSocket@13619f0],behavior=CLIENT,connection=WebSocketClientConnection@158E2A94{endp=DecryptedEndPoint@1f1e5a6{api.services-smarthome.de/193.25.80.79:443<->60634,Open,in,out,-,-,60/300000,WebSocketClientConnection@158e2a94}->SelectChannelEndPoint@1ce7280{api.services-smarthome.de/193.25.80.79:443<->60634,Open,in,out,-,-,9/300000,SslConnection@ccef9d}{io=0/0,kio=0,kro=1},ios=IOState@194942d[CONNECTED,!in,out],f=Flusher[queueSize=0,aggregateSize=0,failure=null],g=Generator[CLIENT,validating],p=Parser@15892ac[ExtensionStack,s=START,c=0,len=0,f=null]},remote=WebSocketRemoteEndpoint@1eab7b5[batching=true],incoming=JettyAnnotatedEventDriver[org.openhab.binding.innogysmarthome.internal.InnogyWebSocket@13619f0],outgoing=ExtensionStack[queueSize=0,extensions=[],incoming=org.eclipse.jetty.websocket.common.WebSocketSession,outgoing=org.eclipse.jetty.websocket.client.io.WebSocketClientConnection]]
```

**Comment by ollie-dev** [comment]
Should be fixed with commit af9c6b6d0e962d58d546674f8f4f5a3d7ea6b77f.
